version: "3"
services:
  mysql:
    image: mysql:8
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mydb
    ports:
      - "3305:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
      - mysql-log-volume:/var/log/mysql

volumes:
  mysql-volume:
  mysql-log-volume:
