version: "3"
services:
  mongodb:
    image: mongo:4.4
    container_name: my-mongodb-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mymongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-volume:/data/db
    command: ["mongod", "--bind_ip_all"]  # Specify the command to run

volumes:
  mongodb-volume: